### ISSUE TITLE
Problem about dumping the model

### ISSUE THREAD

**Issue by wang-lx** [rshin/seq2struct#10]
Hi rshin,
Recently, I have read your paper "Encoding Database Schemas with Relation-Aware Self-Attention for Text-to-SQL Parsers". It's really an excellent work. And I have learned a lot from the code that achieved relation-aware self attention in pytorch.
But there is a bug about dumping the model when I run your command when training. And the config used is 02-20.jsonnet. So could you tell me how to run the latest config file correctly?
Thanks for your patience, looking forward to your response!

**Comment by rshin** [comment]
Thanks for your interest! The README was out of date, and I have updated it to conform to the paper you mentioned. Please reopen the issue and let me know if it doesn't work.

**Comment by wang-lx** [comment]
![image](https://user-images.githubusercontent.com/32166620/63020300-54ff4000-bed0-11e9-9ea7-d989fbee3145.png)
![image](https://user-images.githubusercontent.com/32166620/63020385-8d9f1980-bed0-11e9-8638-9cf98355ec2e.png)

Sorry to bother you again. The problem about dumping the model are still exist.
This will occur when the model is saved for the second time.
Look forward to your reply. Thank you so much.

**Comment by rshin** [comment]
Yes, you can delete lines 72-75 if you want, but then `model_checkpoint` will no longer point to the latest checkpoint. I think there may be some problem with relative paths. Try using an absolute path instead.
